title:               Josh Machado - My Research
url:                 https://joshmachado.github.io/research_projects
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Josh Machado
  url:               joshmachado.github.io
  email:             machado.35@osu.edu

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
